project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs

website:
  page-navigation: true
  title: "DataFest!"
  description: "Homepage for DataFest! - {{< var datafest.term >}} at Davidson College"
  site-url: https://pebenbow.github.io/datafest-quarto/
  repo-url: https://github.com/pebenbow/datafest-quarto
  issue-url: https://github.com/pebenbow/datafest-quarto/issues/new/choose
  repo-actions: [issue]

  navbar:
    background: "#d42121"
    logo: "images/davidson-wordmark-lockup-on red.png"
    logo-alt: "Davidson College wordmark"
    pinned: true
    align: center

    # style: docked
    search: true
    collapse-level: 2
    left:
      - href: index.qmd
        text: Home
      - href: presentation.qmd
        text: Slide Deck
      - href: r-example.qmd
        text: R Example
      - href: py-example.qmd
        text: Python Example

    tools:
      - icon: github
        href: https://github.com/pebenbow/datafest-quarto
        text: GitHub

  page-footer:
    left: "This page is built with [Quarto](https://quarto.org/)"
    background: "#d42121"
    foreground: "#FFFFFF"

format:
  html:
    theme:
      light: [cosmo, style/light.scss]
      dark: [cosmo, style/light.scss, style/dark.scss]
    linkcolor: "#d42121"
    lightbox: true
    fig-width: 10
    fig-height: 6
    toc: true
    code-copy: true
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#d42121"
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto
  cache: true

editor: source

jupyter: python3